# Generated by Django 4.2.3 on 2023-11-04 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
