version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - ./static:/app/static
    ports:
      - 8000:8000
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - web
