# Generated by Django 4.2.3 on 2023-12-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start']},
        ),
        migrations.AddField(
            model_name='appointmentssettings',
            name='booked_slots_blocking_count',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='This many preceding or following slots will prevent booking other slots'),
        ),
        migrations.AlterField(
            model_name='appointmentssettings',
            name='adjacent_slot_frame_in_minutes',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Consider adjacent other slots that end within this amount of minutes from the start of each other'),
        ),
        migrations.AlterField(
            model_name='appointmentssettings',
            name='parallel_slot_frame_in_minutes',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Consider parallel other slots that start within this number of minutes from each other'),
        ),
    ]
