# Generated by Django 4.2.3 on 2023-12-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_slot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentssettings',
            name='booked_slots_blocking_count',
        ),
        migrations.AddField(
            model_name='appointmentssettings',
            name='booked_adjacent_slots_blocking_count',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='This many preceding or following slots will affect the booking of parallel slots'),
        ),
        migrations.AddField(
            model_name='appointmentssettings',
            name='booked_parallel_slots_blocking_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='This amount of booked parallel slots will affect the booking of parallel slots'),
        ),
    ]
