# Generated by Django 4.2.3 on 2023-12-31 13:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_billinginfo_order_remove_shopsettings_vat_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='net_price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.19, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='vat'),
        ),
    ]
