# Generated by Django 4.2.3 on 2024-01-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderitem_net_price_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='order_number_lower_limit',
            field=models.PositiveIntegerField(default=100000, help_text='Order numbers are a randomly generated number with at least this value', verbose_name='Order number smallest possible value'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='order_number_upper_limit',
            field=models.PositiveIntegerField(default=999999, help_text='Order numbers are a randomly generated number with this value at the most', verbose_name='Order number largest possible value'),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='street',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='street_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_info',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='shop.billinginfo'),
        ),
    ]
