# Generated by Django 4.2.3 on 2024-01-01 14:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_base_order_base_total_order_gross_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='subtotal',
            new_name='gross_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vat',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='vat_factor'),
        ),
    ]
