# Generated by Django 4.2.3 on 2024-01-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_billinginfo_email_alter_orderitem_net_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vat',
            new_name='vat_factor',
        ),
    ]
