# Generated by Django 4.2.3 on 2023-07-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevent_bookings_after_date', models.DateField()),
                ('prevent_bookings_after_days', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo_alt', models.CharField(blank=True, max_length=128, null=True, verbose_name='Alt text')),
                ('theme_colour', models.CharField(default='999999', max_length=6, verbose_name='Colour Hexagesimal')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('duration', models.PositiveSmallIntegerField(default=60, verbose_name='Duration')),
                ('buffer', models.PositiveSmallIntegerField(default=30, verbose_name='Buffer')),
                ('is_protected', models.BooleanField(default=False, verbose_name='protect')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='disable')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.room', verbose_name='room')),
            ],
            options={
                'ordering': ['room', 'start'],
            },
        ),
    ]
