# Generated by Django 4.2.3 on 2023-07-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='is_disabled',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='is_protected',
        ),
        migrations.AddField(
            model_name='slot',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.room', verbose_name='Room'),
        ),
    ]
