# Generated by Django 4.2.3 on 2023-07-14 11:42

import apps.appointments.models.appointments_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_slot_is_disabled_remove_slot_is_protected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevent_bookings_after_date', models.DateField(default=apps.appointments.models.appointments_settings.default_prevent_bookings_after_date, verbose_name='Prevent bookings after date')),
                ('prevent_bookings_after_days', models.PositiveSmallIntegerField(default=90, verbose_name='Prevent bookings after days')),
                ('buffer_in_minutes', models.PositiveSmallIntegerField(default=180, verbose_name='Buffer in minutes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CalendarSettings',
        ),
    ]
