# Generated by Django 4.2.3 on 2023-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointmentssettings_booked_slots_blocking_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentssettings',
            name='booked_distant_slots_block_minutes',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='Block slots this many minutes away from other slots on the same day'),
        ),
        migrations.AlterField(
            model_name='appointmentssettings',
            name='booked_adjacent_slots_blocking_count',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='This many booked preceding or following slots will affect the availability of other slots'),
        ),
        migrations.AlterField(
            model_name='appointmentssettings',
            name='booked_parallel_slots_blocking_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='This amount of booked parallel slots will affect the availability of other slots'),
        ),
    ]
