# Generated by Django 4.2.3 on 2023-07-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='days_of_week',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=32),
        ),
    ]
