# Generated by Django 4.2.3 on 2023-12-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentssettings_booked_distant_slots_block_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='slot',
            name='availability',
            field=models.PositiveBigIntegerField(choices=[(1, 'Default'), (2, 'Disabled'), (3, 'Ignore blocked by adjacent')], default=1, verbose_name='availability'),
        ),
    ]
