# Generated by Django 4.2.3 on 2023-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_schedule_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='buffer_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
