# Generated by Django 4.2.3 on 2023-07-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_schedule_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='appointment_end',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='block_end',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='days_of_week',
            field=models.CharField(max_length=50),
        ),
    ]
