# Generated by Django 4.2.3 on 2023-07-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_slot_appointment_end_slot_block_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='repeat_times',
            field=models.IntegerField(default=1, help_text='The number of slots to be created each day', verbose_name='Repeat times'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.room', verbose_name='Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='schedule',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.schedule', verbose_name='Schedule'),
        ),
    ]
