# Generated by Django 4.2.3 on 2023-07-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_schedule_repeat_times_schedule_room_slot_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='schedule',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', related_query_name='slots', to='appointments.schedule', verbose_name='Schedule'),
        ),
    ]
