# Generated by Django 4.2.3 on 2023-08-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_slot_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentssettings',
            name='adjacent_slot_frame_in_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Consider adjacent other slots that end within this amount of minutes from the start of each other'),
        ),
        migrations.AddField(
            model_name='appointmentssettings',
            name='parallel_slot_frame_in_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Consider parallel other slots that start within this number of minutes from each other'),
        ),
    ]
