# Generated by Django 4.2.3 on 2023-08-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_appointmentssettings_adjacent_slot_frame_in_minutes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentssettings',
            options={'verbose_name_plural': ' Settings'},
        ),
    ]
