# Generated by Django 4.2.3 on 2023-08-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0013_appointmentssettings_adjacent_slot_frame_in_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Shipping cost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.room', verbose_name='Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
