# Generated by Django 4.2.3 on 2023-08-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointmentproductgroup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='appointmentproductgroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='voucherproductgroup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='voucherproductgroup',
            name='name',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productgroup', verbose_name='Group')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentproductgroup',
            name='productgroup_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.productgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucherproductgroup',
            name='productgroup_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.productgroup'),
            preserve_default=False,
        ),
    ]
