# Generated by Django 4.2.3 on 2023-09-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='days_valid',
            field=models.PositiveIntegerField(default=365, verbose_name='Expiration date'),
        ),
    ]
