# Generated by Django 4.2.3 on 2023-08-26 09:35

import apps.shop.models.coupon
import common.days_of_week_mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productgroup_remove_appointmentproductgroup_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_coupon_code_length', models.PositiveSmallIntegerField(default=8, verbose_name='Default coupon length')),
                ('default_coupon_validity_in_days', models.PositiveSmallIntegerField(default=365, verbose_name='Default coupon validity in days')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, verbose_name='Reference')),
                ('code', models.SlugField(blank=True, max_length=32, unique=True, verbose_name='code')),
                ('combines', models.BooleanField(default=True, verbose_name='Combinable')),
                ('use_counter', models.IntegerField(default=0, verbose_name='Use courter')),
                ('use_limit', models.IntegerField(default=1, verbose_name='Usage limit')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('expiry', models.DateField(blank=True, default=apps.shop.models.coupon.default_expiry_calc, null=True, verbose_name='Expiration date')),
                ('minimum_spend', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Minimum spend')),
                ('days_of_week', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Product')),
                ('product_included', models.ManyToManyField(blank=True, related_name='product_include', to='shop.product', verbose_name='include product')),
            ],
            bases=(models.Model, common.days_of_week_mixin.DaysOfWeekMixin),
        ),
    ]
