# Generated by Django 4.2.3 on 2023-09-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_coupon_days_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Created'),
        ),
    ]
