# Generated by Django 4.2.3 on 2023-11-11 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('shop', '0004_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemappointment',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.slot', verbose_name='slot'),
        ),
    ]
