# Generated by Django 4.2.3 on 2023-08-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_appointmentssettings_options'),
        ('shop', '0005_shopsettings_coupon_code_characters_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentProductGroup',
            new_name='ProductGroupAppointment',
        ),
        migrations.RenameModel(
            old_name='VoucherProductGroup',
            new_name='ProductGroupCoupon',
        ),
        migrations.AlterModelOptions(
            name='shopsettings',
            options={'verbose_name_plural': ' Settings'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.SlugField(blank=True, max_length=32, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='days_of_week',
            field=models.CharField(default='[0, 1, 2, 3, 4, 5 ,6]', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='coupon_code_characters',
            field=models.CharField(default='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', help_text='Any lower case letters will be capitalized, avoid duplicate characters', max_length=64, verbose_name='Coupon default used characters'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='default_coupon_code_length',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Coupon code default length'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='default_coupon_validity_in_days',
            field=models.PositiveSmallIntegerField(default=365, verbose_name='Coupon default validity in days'),
        ),
    ]
