# Generated by Django 4.2.3 on 2023-11-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('shop', '0006_alter_cartitemappointment_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemappointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_appointment', to='appointments.slot', verbose_name='slot'),
        ),
    ]
