# Generated by Django 4.2.3 on 2023-08-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_coupon_apply_to_entire_cart_coupon_is_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.SlugField(blank=True, help_text='Only ascii characters', max_length=32, verbose_name='Code'),
        ),
    ]
