# Generated by Django 4.2.3 on 2023-08-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_appointmentssettings_options'),
        ('shop', '0009_alter_coupon_code_cartproduct_cartcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProductCoupon',
            fields=[
                ('cartproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.cartproduct')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.coupon', verbose_name='')),
            ],
            bases=('shop.cartproduct',),
        ),
        migrations.CreateModel(
            name='CartProductAppointment',
            fields=[
                ('cartproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.cartproduct')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.slot', verbose_name='')),
            ],
            bases=('shop.cartproduct',),
        ),
    ]
