# Generated by Django 4.2.3 on 2023-09-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_appointmentssettings_options'),
        ('shop', '0010_cartproductcoupon_cartproductappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductappointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.slot', verbose_name='slot'),
        ),
        migrations.AlterField(
            model_name='cartproductcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.coupon', verbose_name='coupon'),
        ),
    ]
