# Generated by Django 4.2.3 on 2024-01-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shopsettings_order_number_lower_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='default_coupon_code_chars',
            field=models.SlugField(default='ABCDEFHJKMNPQRSTWXYZ123489', help_text='Any lower case letters will be capitalized, avoid duplicate characters', max_length=32, verbose_name='Coupon default used characters'),
        ),
    ]
