# Generated by Django 4.2.3 on 2024-01-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_shopsettings_default_coupon_code_chars'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shop.billinginfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(db_index=True, editable=False, unique=True),
        ),
    ]
