# Generated by Django 4.2.3 on 2024-01-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_base_alter_order_billing_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='base',
            new_name='base_total',
        ),
        migrations.AddField(
            model_name='order',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
    ]
