# Generated by Django 4.2.3 on 2023-09-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0012_product_real_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='real_type',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='real_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
