# Generated by Django 4.2.3 on 2023-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_product_real_type_productgroup_real_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='VAT'),
        ),
    ]
