# Generated by Django 4.2.3 on 2024-01-02 13:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_subtotal_orderitem_gross_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='net_price'),
        ),
    ]
