# Generated by Django 4.2.3 on 2023-09-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_shopsettings_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='vat',
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='vat_percent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='VAT'),
        ),
    ]
